### ISSUE TITLE
warm shutdown on heroku and long jobs

### ISSUE THREAD

**Issue by samuelcolvin** [rq/rq#584]
We have some jobs which run on a heroku worker and take quite a long time lets say 1-10 minutes.

As per [this](http://support.hirefire.io/discussions/problems/31480-valid-jobs-being-moved-to-failed-in-rq-on-warm-shutdown) or due to heroku restarting dynos these jobs occasionally recieve the `SIGTERM` signal and then shutdown.

Since the jobs are unlikely to end in the 10 second grace period Heroku give before killing the dyno the right thing to do here would be to raise an Exception and let the job fail. Then our standard code for recording and dealing with errors would work.

I've tried adding a handler to `SIGTERM` to do this however it's not being called because of [_install_signal_handlers](https://github.com/nvie/rq/blob/bb4336f612910f33ed72359a3f8b690b4acf8a4a/rq/worker.py#L321-L366). Because the jobs are eventually killed by the worker shutting down we're not getting an exception raised or sent to sentry, similarly the job doesn't seem to appear in the failed queue until it's exceed it's timeout (or perhaps "cleanup" deals with it, I don't know).

What's the best solution here?

All I can think of here is to create a custom worker and overwrite `_install_signal_handlers`. If that's the correct solution can I suggest defining `request_force_stop` and `request_stop` outside `_install_signal_handlers` so less code has to be duplicated?

**Comment by samuelcolvin** [comment]
I've looked into this in more detail main problem (and I think it's quite a big problem) is [this](https://github.com/nvie/rq/blob/0.5.5/rq/worker.py#L528).

The work horse is terminated as soon as it receives `SIGTERM`. Heroku sends SIGTERM to all processes on the dyno 10 seconds before it shuts it down see [here](https://devcenter.heroku.com/articles/dynos#shutdown). 

> This signal is sent to all processes in the dyno, not just the process type.

This means on Heroku that none of rq's warm/cold shutdown, wait for jobs to finish logic is being called at all - as soon as a dyno starts to shut down all jobs are killed immediately with no exception or traceback.

My personal solution is to send `SIGRTMIN` to `horse_pid` in `request_stop`, that way most jobs won't be affected and might well finish before the 10 second grace period runs out, but processes which won't finished can handle `SIGRTMIN` and throw an exception, we can even use `frame` to get some information about the state of the job when the signal was received. 

A more sophisticated approach might be to send another signal to the work horse x seconds after the first `SIGTERM` which causes the job to throw an exception so an exception is always thrown before a job is terminated. So something like:
* on first `SIGTERM`, `SIGRTMIN` is sent to `horse_pid`, by default this does nothing but jobs can act on it if they wish.
* 5 seconds after the first `SIGTERM`, `SIGRTMIN+1` is sent to `horse_pid` this is handled by the worker or job which raises an exception.


Either way, I think rq should definitely:
* move `request_force_stop` and `request_stop` out of `_install_signal_handlers` so they can be overridden independently. This is minor but would be useful, I'm happy to submit a PR to do it if people think it would be useful?
* put a prominent message somewhere saying that none of rq's normal shutdown logic is being executed on Heroku.
* provide some reasonably easy to warn jobs that they are imminently going to get abruptly terminated.

**Comment by selwin** [comment]
Thanks for the detailed explanation. I think what you said makes sense, would be glad to merge in a PR for that :)

**Comment by selwin** [comment]
Fixed in https://github.com/nvie/rq/issues/587

**Comment by samuelcolvin** [comment]
This isn't fixed yet. I'll try and do a PR this week to fix it.

**Comment by selwin** [comment]
@samuelcolvin whoops, sorry about that. What other changes are you planning on making? I'll reopen the issue for now.

**Comment by boxbeatsy** [comment]
Hi @samuelcolvin , we're experiencing this same issue and are attempting to follow your advice.  Do you by any chance have an example of how you're handling SIGRTMIN? Would be greatly appreciated!

**Comment by boxbeatsy** [comment]
This issue seems to address the same problem, but is also unresolved: https://github.com/nvie/rq/issues/152

**Comment by samuelcolvin** [comment]
Hi guys, sorry for the long delay on this.

TutorCruncher has a solution for this we've been using with Heroku and RQ for about 6 months now. It's been working well, but I wasn't quite sure about the best way to contribute the solution to RQ itself (also I got distracted by other things).

I just put the customer worker we use in a [gist here](https://gist.github.com/samuelcolvin/65558cdcaddd83848abd57f9a5955e21). @boxbeatsy, please note: this is just copy and pasted from our codebase with other customisations removed, it might well not work out of the box, comment on it if you have trouble and I'll try to help.

In terms of a proper solution for RQ itself: I would imagine people would be unwilling to change the default worker to use the above, it would be a fairly big change and testing it thoroughly is very hard. @selwin would you agree?

Perhaps the best solution if others want to use the worker would be to add `HerokuWorker` to RQ and let people use that if they wish. If you don't like that idea I guess it could be a separate package in pypi, but personally that feels like an inferior solution.

By the way, @selwin @nvie is there a plan to do a new release any time soon? My changes in #587 are still not released so the custom worker above has to duplicate quite a lot of code.

**Comment by boxbeatsy** [comment]
@samuelcolvin this worked out of the box perfectly, thank you!!!!  

I've submitted a ticket to Heroku to update their documentation here (https://devcenter.heroku.com/articles/python-rq) to reference this aspect of the RQ library so others can pre-empt the issue.

**Comment by selwin** [comment]
@samuelcolvin I like your gist. Some observations:

1. When a horse gets killed, it raises an exception. This allows us to record cold shutdowns, the exception may also contain useful information about it's current execution status. This will be even more important for custom workers that supports concurrency.

2. Horses ignore `SIGINT` and `SIGTERM` and only responds to `SIGRTMIN` sent by the main worker. I can live with this if it makes RQ more reliable on platforms like Heroku.

3. Horses automatically perform hard shutdown X seconds after `SIGRTMIN` is received. Can we modify this to mimic RQ's current behavior? It should only perform hard shutdown after receving `SIGRTMIN` for the second time.

When you're free, please consider making a PR :)

Regarding a new release; yes, looking through the commits logs, we've actually added a significant number of polishes ever since the last release. I'll try to prepare a changelog this weekend so we can release 0.6.0.

**Comment by jezdez** [comment]
Hey, one thing I noticed is that the `SIGRTMIN` signal isn't available on macOS and so the tests fail when running tox on it. I think we should skip them when, see #763.

**Comment by antoine-lizee** [comment]
I'm adding these to the docs in #771

**Comment by selwin** [comment]
Fixed in 
https://github.com/rq/rq/pull/715
